### ISSUE TITLE
Cannot unset --markers  value for run_gatk_pileup_for_sample.py

### ISSUE THREAD

**Issue by mmokrejs** [nygenome/Conpair#4]
Hi,
  I aligned using GRCH38 reference so teh default GRCH37-based setting cannot be used in my case. How can I unset the value? It seems it is optional but is not documented.

Thank you for your help

**Comment by ewabergmann** [comment]
Hi Martin,

You 'unset' the value by specifying another reference genome file (fasta.qz).

In order to be able use the fasta file as a reference 2 additional files are required: [reference_genome].dict, [reference_genome].fa.fai
To create these files please follow: http://gatkforums.broadinstitute.org/gatk/discussion/1601/how-can-i-prepare-a-fasta-file-to-use-as-reference

Please keep in mind that the marker set we provide with the tool has only been verified and tested for GRCh37.

Hope this helps!
Ewa
